import { useEffect, useState } from 'react';
import { Alert, Pressable, Share, StyleSheet, Text, View } from 'react-native';
import { File } from 'expo-file-system';
import { useRouter } from 'expo-router';

import { FinancePage } from '@/components/layout/finance-page';
import { createBudget, createCategory, createTransaction, deleteTransaction, getApiBaseUrl, type ApiCategory, type ApiTransaction } from '@/lib/api';
import { clearAuthUser, getAuthUser, type AuthUser } from '@/lib/auth';
import { clearCachedTransactions, saveBudgets, saveCategories, saveTransactions } from '@/lib/sqlite';
import { useFinanceStore } from '@/store/finance-store';

const csvEscape = (value: unknown) => `"${String(value ?? '').replaceAll('"', '""')}"`;
const parseCsvLine = (line: string) => { const values: string[] = []; let value = ''; let quoted = false; for (let i = 0; i < line.length; i += 1) { const character = line[i]; if (character === '"' && quoted && line[i + 1] === '"') { value += '"'; i += 1; } else if (character === '"') quoted = !quoted; else if (character === ',' && !quoted) { values.push(value.trim()); value = ''; } else value += character; } values.push(value.trim()); return values; };

export default function SettingsScreen() {
  const router = useRouter(); const [user, setUser] = useState<AuthUser | null>(null); const [busy, setBusy] = useState<string | null>(null);
  const { budgets, categories, setBudgets, setCategories, setTransactions, transactions } = useFinanceStore();
  useEffect(() => { void getAuthUser().then(setUser); }, []);

  const shareText = async (name: string, text: string) => { await Share.share({ title: name, message: text }); };
  const exportCsv = async () => { setBusy('csv'); try { const csv = ['date,type,amount,category,description,merchant,tags', ...transactions.map((item) => [item.date, item.type, item.amount, item.category, item.description, item.merchant, item.tags?.join('|')].map(csvEscape).join(','))].join('\n'); await shareText(`save-personal-${Date.now()}.csv`, csv); } catch { Alert.alert('Export failed', 'The CSV could not be shared.'); } finally { setBusy(null); } };
  const exportBackup = async () => { setBusy('backup'); try { await shareText(`save-backup-${Date.now()}.json`, JSON.stringify({ version: 1, exportedAt: new Date().toISOString(), transactions, categories, budgets }, null, 2)); } catch { Alert.alert('Export failed', 'The backup could not be shared.'); } finally { setBusy(null); } };
  const restore = async () => { const selected = await File.pickFileAsync({ mimeTypes: 'application/json' }); if (selected.canceled) return; setBusy('restore'); try { const raw = await selected.result.text(); const backup = JSON.parse(raw) as { transactions?: ApiTransaction[]; categories?: ApiCategory[]; budgets?: typeof budgets }; if (!Array.isArray(backup.transactions) || !Array.isArray(backup.categories)) throw new Error('invalid'); const restoredCategories = await Promise.all(backup.categories.map(({ id: _id, ...item }) => createCategory(item))); const restoredTransactions = await Promise.all(backup.transactions.map(({ id: _id, ...item }) => createTransaction(item))); const restoredBudgets = backup.budgets ? await Promise.all(backup.budgets.map(({ id: _id, spent: _spent, ...item }) => createBudget(item))) : []; setCategories([...categories, ...restoredCategories]); setTransactions([...transactions, ...restoredTransactions]); setBudgets([...budgets, ...restoredBudgets]); saveCategories([...categories, ...restoredCategories]); saveTransactions([...transactions, ...restoredTransactions]); saveBudgets([...budgets, ...restoredBudgets]); Alert.alert('Backup restored', `${restoredTransactions.length} transactions were imported.`); } catch { Alert.alert('Restore failed', 'Choose a valid SAVE JSON backup.'); } finally { setBusy(null); } };
  const importCsv = async () => { const selected = await File.pickFileAsync({ mimeTypes: ['text/csv', 'text/comma-separated-values', 'text/plain'] }); if (selected.canceled) return; setBusy('import'); try { const rows = (await selected.result.text()).split(/\r?\n/).filter(Boolean).map(parseCsvLine); const headers = rows.shift()?.map((header) => header.toLowerCase()) ?? []; const dateIndex = headers.indexOf('date'); const amountIndex = headers.indexOf('amount'); if (dateIndex < 0 || amountIndex < 0) throw new Error('missing columns'); const categoryIndex = headers.indexOf('category'); const descriptionIndex = headers.indexOf('description'); const typeIndex = headers.indexOf('type'); const merchantIndex = headers.indexOf('merchant'); const imported: ApiTransaction[] = []; const createdCategories: ApiCategory[] = []; for (const row of rows) { const amount = Number(row[amountIndex]); if (!row[dateIndex] || !Number.isFinite(amount) || amount <= 0) continue; const type = row[typeIndex] === 'income' ? 'income' : 'expense'; const category = row[categoryIndex] || 'Imported'; if (![...categories, ...createdCategories].some((item) => item.name.toLowerCase() === category.toLowerCase() && item.type === type)) createdCategories.push(await createCategory({ name: category, type, color: type === 'income' ? '#22c55e' : '#5ca9ff' })); imported.push(await createTransaction({ userId: 'usr_2', date: row[dateIndex], amount, type, category, description: row[descriptionIndex] || 'Imported transaction', merchant: row[merchantIndex] || undefined, status: 'approved' })); } const nextTransactions = [...transactions, ...imported]; const nextCategories = [...categories, ...createdCategories]; setTransactions(nextTransactions); setCategories(nextCategories); saveTransactions(nextTransactions); saveCategories(nextCategories); Alert.alert('CSV imported', `${imported.length} transactions and ${createdCategories.length} new categories were added.`); } catch { Alert.alert('Import failed', 'The CSV must include date and amount columns.'); } finally { setBusy(null); } };
  const clearAll = () => Alert.alert('Clear all expenses?', 'This permanently deletes all income and expense records. Categories and custom fields are preserved.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Clear All', style: 'destructive', onPress: () => void (async () => { setBusy('clear'); try { await Promise.all(transactions.map((item) => deleteTransaction(item.id))); setTransactions([]); clearCachedTransactions(); Alert.alert('Expenses cleared'); } catch { Alert.alert('Clear failed', 'The expense API is unavailable. No local data was cleared.'); } finally { setBusy(null); } })() }]);

  return <FinancePage title="Settings" subtitle="Data, currency, and account preferences">
    <View style={styles.card}><Text style={styles.cardTitle}>Currency</Text><Text style={styles.label}>Default Currency</Text><Pressable style={styles.select} onPress={() => Alert.alert('Default currency', 'PHP — Philippine Peso is the supported display currency in this phase.')}><Text style={styles.selectText}>PHP — Philippine Peso</Text><Text style={styles.selectText}>⌄</Text></Pressable><Text style={styles.help}>Changing currency affects display only. Existing expenses retain their stored amounts.</Text></View>
    <View style={styles.card}><Text style={styles.cardTitle}>Data Management</Text><DataButton label={busy === 'csv' ? 'Creating CSV…' : '⇩  Export CSV (personal)'} onPress={exportCsv} disabled={Boolean(busy)} /><DataButton label={busy === 'backup' ? 'Creating backup…' : '⇩  Export Full Backup'} onPress={exportBackup} disabled={Boolean(busy)} /><DataButton label={busy === 'restore' ? 'Restoring…' : '⇧  Restore from Backup (JSON)'} onPress={restore} disabled={Boolean(busy)} /><View style={styles.divider} /><Text style={styles.label}>Import from CSV</Text><Text style={styles.help}>Import expenses from a CSV file. It must include <Text style={styles.code}>date</Text> and <Text style={styles.code}>amount</Text> columns. New categories are created automatically.</Text><Text style={styles.importLabel}>Import into:  <Text style={styles.personal}>Personal</Text></Text><DataButton label={busy === 'import' ? 'Importing…' : '⇧  Choose CSV File to Import'} onPress={importCsv} disabled={Boolean(busy)} /><View style={styles.divider} /><Pressable disabled={Boolean(busy)} style={styles.danger} onPress={clearAll}><Text style={styles.dangerText}>{busy === 'clear' ? 'Clearing…' : '♲  Clear All Expenses'}</Text></Pressable><Text style={styles.help}>This clears expenses and receipts only. Categories and custom fields are preserved.</Text></View>
    <View style={styles.card}><Text style={styles.cardTitle}>Profile</Text><Text style={styles.profile}>{user?.name ?? 'No profile'}</Text><Text style={styles.help}>{user?.email ?? 'Complete onboarding'} · API {getApiBaseUrl()}</Text><Pressable style={styles.profileButton} onPress={() => router.push('/onboarding')}><Text style={styles.profileButtonText}>Edit profile</Text></Pressable></View>
    <Pressable style={styles.signout} onPress={async () => { await clearAuthUser(); router.replace('/onboarding'); }}><Text style={styles.signoutText}>Sign out</Text></Pressable>
  </FinancePage>;
}
function DataButton({ label, onPress, disabled }: { label: string; onPress: () => void; disabled: boolean }) { return <Pressable disabled={disabled} style={[styles.dataButton, disabled && styles.disabled]} onPress={onPress}><Text style={styles.dataButtonText}>{label}</Text></Pressable>; }
const styles = StyleSheet.create({
  card: { backgroundColor: '#0d1629', borderWidth: 1, borderColor: '#1d2a42', borderRadius: 12, padding: 18, gap: 13 }, cardTitle: { color: '#f2f6fb', fontSize: 19, fontWeight: '800', marginBottom: 5 }, label: { color: '#e5ebf5', fontSize: 14, fontWeight: '700' }, select: { backgroundColor: '#081120', borderWidth: 1, borderColor: '#26354e', borderRadius: 9, padding: 15, flexDirection: 'row', justifyContent: 'space-between' }, selectText: { color: '#e7edf7', fontSize: 15 }, help: { color: '#8c99ad', fontSize: 12, lineHeight: 18 }, dataButton: { backgroundColor: '#09111f', borderWidth: 1, borderColor: '#26354e', borderRadius: 9, padding: 14, alignItems: 'center' }, dataButtonText: { color: '#e8eef7', fontWeight: '700', fontSize: 14 }, disabled: { opacity: 0.55 }, divider: { height: 1, backgroundColor: '#26334b', marginVertical: 2 }, code: { backgroundColor: '#18243a', color: '#aebbd0' }, importLabel: { color: '#9aa7ba', fontSize: 12 }, personal: { color: '#07111f', backgroundColor: '#5ca9ff', fontWeight: '800' }, danger: { backgroundColor: '#da464c', borderRadius: 9, padding: 15, alignItems: 'center' }, dangerText: { color: '#fff', fontWeight: '800', fontSize: 15 }, profile: { color: '#eff4fb', fontWeight: '800' }, profileButton: { borderWidth: 1, borderColor: '#315176', borderRadius: 9, padding: 12, alignItems: 'center' }, profileButtonText: { color: '#69afff', fontWeight: '700' }, signout: { backgroundColor: '#291522', padding: 14, borderRadius: 9, alignItems: 'center' }, signoutText: { color: '#ff788c', fontWeight: '800' },
});
